export { default as addPost } from './addPost.svg';
export { default as avatar } from './avatar.svg';
export { default as bigLogo } from './bigLogo.svg';
export { default as folder } from './folder.svg';
export { default as location } from './location.svg';
export { default as logo } from './logo.svg';
export { default as scrapBg } from './scrapBg.svg';
export { default as tempPost } from './tempPost.svg';
export { default as worldMap } from './worldMap.svg';
