import Head from 'next/head';

import { useGetPersonalTravelogues } from '@/api/hooks/travelogue';

// import { TravelogueList } from '@/components/Travelogue';

export default function Home() {
  const { data } = useGetPersonalTravelogues({
    size: 5,
  });

  console.log(data?.pages);

  return (
    <>
      <Head>
        <title>Travel.zip</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div>하이</div>
        {/* <TravelogueFeed /> */}
      </main>
    </>
  );
}
